Models/ErrorViewModel.cs
namespace a.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/UlohaModel.cs
namespace stejskal_4D_hello_aspnet.Models
{
    public class UserInfo
    {
        public string Name { get; set; } = "";
        public string Email { get; set; } = string.Empty;
        public string Tel { get; set; } = "";
        public string UserName { get; set; } = "";
        
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using a.Models;

namespace a.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/UlohyController.cs
using Microsoft.AspNetCore.Mvc;
using stejskal_4D_hello_aspnet.Models;

namespace stejskal_4D_hello_aspnet.Controllers
{
    public class UlohyController : Controller
    {
        public IActionResult Uloha1()
        {
            return View();
        }

        public IActionResult Uloha2()
        {
            return View();
        }
        public IActionResult Uloha3()
        {
            return View();
        }

        public IActionResult Uloha4()
        {
            var userInfoList = new List<UserInfo>()
            {
                new UserInfo {
                    Name = "Jude",
                    Email = "test@gmail.com",
                    Tel = "0910358423",
                    UserName = "Belligoal"
                },
                new UserInfo {
                    Name = "Samo",
                    Email = "test123@gmail.com",
                    Tel = "0910546423",
                    UserName = "Dybala"
                }

            };
            return View(userInfoList);
        } 

        public IActionResult Uloha5()
        {
            var userInfoList = new List<UserInfo>()
            {
                new UserInfo {
                    Name = "Jude",
                    Email = "test@gmail.com",
                    Tel = "0910358423",
                    UserName = "Belligoal"
                },
                new UserInfo {
                    Name = "Samo",
                    Email = "test123@gmail.com",
                    Tel = "0910546423",
                    UserName = "Dybala"
                },new UserInfo {
                    Name = "Jano",
                    Email = "jano@gmail.com",
                    Tel = "09105766323",
                    UserName = "Janci"
                }

            };
            return View(userInfoList);
        } 

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">dybala</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Home Page</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/a.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="Uloha1">Uloha 1</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="Uloha2">Uloha 2</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="Uloha3">Uloha 3</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="Uloha4">Uloha 4</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="Uloha5">Uloha 5</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - a - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_UserCard.cshtml
@using stejskal_4D_hello_aspnet.Models
@model UserInfo


<div>
    <h1>@Model.Name</h1>
    <p>Email: @Model.Email</p>
    <p>Tel: @Model.Tel</p>
</div>

Views/ulohy/Uloha1.cshtml
<div class="text-center">
    <h1 class="display-4">Vitaj na stránke</h1>
    <p>toto je jednoducha podstranka</p>
    <a href="/"><button class="btn1" >Spať na home</button></a>
    
</div>

Views/ulohy/Uloha2.cshtml
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/a.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/uloha2.css" asp-append-version="true" />
</head>
<div class="container2">
    <img src="~/img/belligoal.png" alt="profile pic" class="profile-pic">
    <h1>Jude Bellingham</h1>
    <p>Real Madrid player</p>
    <a href="/"><button class="btn2">Späť</button></a>
</div>

Views/ulohy/Uloha3.cshtml
<head>
    <link rel="stylesheet" href="~/css/uloha3.css" asp-append-version="true" />
</head>

<div class="box">
    @for (int i = 0; i < 6; i++)
    {
        <div class="container3">
            <img src="~/img/belligoal.png" alt="profile pic" class="profile-pic">
            <h2 class="text-center">Jude Bellingham</h2>
            <p>Real Madrid player</p>
        </div>
    }
</div>

Views/ulohy/Uloha4.cshtml
@using stejskal_4D_hello_aspnet.Models
@model List<UserInfo>
<head>
    <link rel="stylesheet" href="~/css/uloha4.css" asp-append-version="true" />
</head>


<div class="table-container">
    <table class="table">
        <thead>
            <tr>Email</tr>
            <tr>Name</tr>
            <tr>Tel</tr>
            <tr>Username</tr>
        </thead>
        <tbody>
            @foreach(var user in Model){
                <tr>
                    <td>
                        @user.Email 
                    </td>
                    <td>
                        @user.Name 
                    </td>
                    <td>
                        @user.Tel 
                    </td>
                    <td>
                        @user.UserName
                    </td>
                </tr>
                }
        </tbody>
        
    </table>
</div>

Views/ulohy/Uloha5.cshtml
@model IEnumerable<stejskal_4D_hello_aspnet.Models.UserInfo>


@foreach (var user in Model)
{
    <partial name="_UserCard" model="user" />
}